CREATE DATABASE DBSistemMonitoringMasaTanam
GO

CREATE TABLE DataTanaman(
	TanamanID INT IDENTITY(1,1) PRIMARY KEY,
	NamaTanaman VARCHAR(50) UNIQUE NOT NULL,
	LamaMasaTanam INT NOT NULL
);

CREATE TABLE DataLahan(
	LahanID INT IDENTITY(1,1) PRIMARY KEY,
	NamaLahan VARCHAR(50) UNIQUE NOT NULL,
	luas_lahan FLOAT NOT NULL
);

CREATE TABLE JadwalTanam(
	JadwalID INT IDENTITY(1,1) PRIMARY KEY,
	TanamanID INT NOT NULL,
	LahanID INT NOT NULL,
	TanggalTanam DATE NOT NULL,
	EstimasiPanen DATE NOT NULL,

	CONSTRAINT FK_Tanaman_ID FOREIGN KEY (TanamanID) REFERENCES DataTanaman(TanamanID) ON DELETE CASCADE,
	CONSTRAINT FK_Lahan_ID FOREIGN KEY (LahanID) REFERENCES DataLahan(LahanID) ON DELETE CASCADE
);



CREATE TABLE Report(
	ReportID INT IDENTITY(1,1) PRIMARY KEY
);

ALTER TABLE DataTanaman
ALTER COLUMN TanamanIDIN